-- WARNING: THIS FILE IS GENERATED, DO NOT MODIFY.


--- <p>The main global game object containing all the game play information.</p>
---@class Game
--- <p>A hash containing all your construction sites with their id as hash keys.</p>
---@field constructionSites table<string,ConstructionSite>
--- <p>A hash containing all your creeps with creep names as hash keys.</p>
---@field creeps table<string,Creep>
--- <p>A hash containing all your flags with flag names as hash keys.</p>
---@field flags table<string,Flag>
--- <p>A hash containing all your power creeps with their names as hash keys. Even power creeps not spawned in the world can be accessed here. </p>
---@field powerCreeps table<string,PowerCreep>
--- <p>A hash containing all the rooms available to you with room names as hash keys. A room is visible if you have a creep or an owned structure in it.</p>
---@field rooms table<string,Room>
--- <p>A hash containing all your spawns with spawn names as hash keys.</p>
---@field spawns table<string,StructureSpawn>
--- <p>A hash containing all your structures with structure id as hash keys.</p>
---@field structures table<string,Structure>
--- <p>System game tick counter. It is automatically incremented on every tick. <a href="https://docs.screeps.com/game-loop.html">Learn more</a></p>
---@field time number
--- <p>Get an object with the specified unique ID. It may be a game object of any type. Only objects from the rooms which are visible to you can be accessed.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>id</code></td><td>string</td><td><p>The unique identificator.</p></td></tr></tbody></table>
---@field getObjectById fun(id:any)
--- <p>Send a custom message at your profile email. This way, you can set up notifications to yourself on any occasion within the game. You can schedule up to 20 notifications during one game tick. Not available in the Simulation Room.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>message</code></td><td>string</td><td><p>Custom text which will be sent in the message. Maximum length is 1000 characters.</p></td></tr><tr><td><code>groupInterval</code></td><td>number</td><td><p>If set to 0 (default), the notification will be scheduled immediately. Otherwise, it will be grouped with other notifications and mailed out later using the specified time in minutes.</p></td></tr></tbody></table>
---@field notify fun(message:any,groupInterval:any?)
---@field cpu Game.cpu
---@field gcl Game.gcl
---@field gpl Game.gpl
---@field map Game.map
---@field market Game.market
---@field resources Game.resources
---@field shard Game.shard
local Game = {}

--- <p>An object containing information about your CPU usage with the following properties:</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>limit</code></td><td>number</td><td><p>Your assigned CPU limit for the current shard.</p></td></tr><tr><td><code>tickLimit</code></td><td>number</td><td><p>An amount of available CPU time at the current game tick.<br/>Usually it is higher than <code>Game.cpu.limit</code>. <a href="https://docs.screeps.com/cpu-limit.html">Learn more</a></p></td></tr><tr><td><code>bucket</code></td><td>number</td><td><p>An amount of unused CPU accumulated in your <a href="https://docs.screeps.com/cpu-limit.html#Bucket">bucket</a>.</p></td></tr><tr><td><code>shardLimits</code></td><td>object<br/>&lt;string,number&gt;</td><td><p>An object with limits for each shard with shard names as keys. You can use <a href="https://docs.screeps.com/api/#Game.setShardLimits"><code>setShardLimits</code></a>method to re-assign them.</p></td></tr><tr><td><code>unlocked</code></td><td>boolean </td><td><p>Whether full CPU is currently unlocked for your account.</p></td></tr><tr><td><code>unlockedTime</code></td><td>number </td><td><p>The time <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime#Syntax" rel="noopener" target="_blank">in milliseconds since UNIX epoch time</a> until full CPU is unlocked for your account. This property is not defined when full CPU is not unlocked for your account or it's unlocked with a subscription.</p></td></tr></tbody></table>
---@class Game.cpu
--- <p><em>This method is only available when <strong>Virtual machine</strong> is set to <strong>Isolated</strong> in your <a href="https://screeps.com/a/#!/account/runtime" rel="noopener" target="_blank">account runtime settings</a>.</em> </p> <p>Use this method to get heap statistics for your virtual machine. The return value is almost identical to the Node.js function <a href="https://nodejs.org/dist/latest-v8.x/docs/api/v8.html#v8_v8_getheapstatistics" rel="noopener" target="_blank"><code>v8.getHeapStatistics()</code></a>. This function returns one additional property: <code>externally_allocated_size</code> which is the total amount of currently allocated memory which is not included in the v8 heap but counts against this isolate's memory limit. <code>ArrayBuffer</code> instances over a certain size are externally allocated and will be counted here.</p>
---@field getHeapStatistics fun():({total_heap_size:integer,total_heap_size_executable:integer,total_physical_size:integer,total_available_size:integer,used_heap_size:integer,heap_size_limit:integer,malloced_memory:integer,peak_malloced_memory:integer,does_zap_garbage:integer,externally_allocated_size:integer})
--- <p>Get amount of CPU time used from the beginning of the current game tick. Always returns 0 in the Simulation mode.</p>
---@field getUsed fun()
--- <p><em>This method is only available when <strong>Virtual machine</strong> is set to <strong>Isolated</strong> in your <a href="https://screeps.com/a/#!/account/runtime" rel="noopener" target="_blank">account runtime settings</a>.</em></p> <p>Reset your runtime environment and wipe all data in heap memory.</p>
---@field halt fun()
--- <p>Allocate CPU limits to different shards. Total amount of CPU should remain equal to  <a href="https://docs.screeps.com/api/#Game.cpu"><code>Game.cpu.shardLimits</code></a>. This method can be used only once per 12 hours.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>limits</code></td><td>object&lt;string, number&gt;</td><td><p>An object with CPU values for each shard in the same format as <code>Game.cpu.shardLimits</code>.</p></td></tr></tbody></table>
---@field setShardLimits fun(limits:any)
--- <p>Unlock full CPU for your account for additional 24 hours. This method will consume 1 CPU unlock bound to your account (See <a href="https://docs.screeps.com/api/#Game.resources"><code>Game.resources</code></a>).If full CPU is not currently unlocked for your account, it may take some time (up to 5 minutes) before unlock is applied to your account.</p>
---@field unlock fun()
--- <p>Generate 1 pixel resource unit for 10000 CPU from your bucket.</p> <table class="api-return-codes"><thead><tr><th>constant</th><th>value</th><th>description</th></tr></thead><tbody><tr><td><code>OK</code></td><td>0</td><td><p>The operation has been scheduled successfully.</p></td></tr><tr><td><code>ERR_NOT_ENOUGH_RESOURCES</code></td><td>-6</td><td><p>Your bucket does not have enough CPU.</p></td></tr></tbody></table>
---@field generatePixel fun()
local cpu = {}

--- <p>Your <a href="https://docs.screeps.com/control.html#Global-Control-Level">Global Control Level</a>, an object with the following properties :</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>level</code></td><td>number</td><td><p>The current level.</p></td></tr><tr><td><code>progress</code></td><td>number</td><td><p>The current progress to the next level.</p></td></tr><tr><td><code>progressTotal</code></td><td>number</td><td><p>The progress required to reach the next level.</p></td></tr></tbody></table>
---@class Game.gcl
local gcl = {}

--- <p>Your Global Power Level, an object with the following properties :</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>level</code></td><td>number</td><td><p>The current level.</p></td></tr><tr><td><code>progress</code></td><td>number</td><td><p>The current progress to the next level.</p></td></tr><tr><td><code>progressTotal</code></td><td>number</td><td><p>The progress required to reach the next level.</p></td></tr></tbody></table>
---@class Game.gpl
local gpl = {}

--- <p>A global object representing world map. Use it to navigate between rooms.</p>
---@class Game.map
--- <p>List all exits available from the room with the given name.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>roomName</code></td><td>string</td><td><p>The room name.</p></td></tr></tbody></table>
---@field describeExits fun(roomName:any):(table<integer,string>)
--- <p>Find the exit direction from the given room en route to another room.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>fromRoom</code></td><td>string, <a href="https://docs.screeps.com/api/#Room">Room</a></td><td><p>Start room name or room object.</p></td></tr><tr><td><code>toRoom</code></td><td>string, <a href="https://docs.screeps.com/api/#Room">Room</a></td><td><p>Finish room name or room object.</p></td></tr><tr><td><code>opts</code><br/><em>optional</em></td><td>object</td><td><p>An object with the pathfinding options. See <code><a href="https://docs.screeps.com/api/#findRoute">findRoute</a></code>.</p></td></tr></tbody></table>
---@field findExit fun(fromRoom:any,toRoom:any,opts:any?)
--- <p>Find route from the given room to another room.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>fromRoom</code></td><td>string, <a href="https://docs.screeps.com/api/#Room">Room</a></td><td><blockquote></blockquote><p>Start room name or room object.</p></td></tr><tr><td><code>toRoom</code></td><td>string, <a href="https://docs.screeps.com/api/#Room">Room</a></td><td><p>Finish room name or room object.</p></td></tr><tr><td><code>opts</code><br/><em>optional</em></td><td>object</td><td><p>An object with the following options:                    </p><ul><li><div class="api-arg-title">routeCallback</div><div class="api-arg-type">function</div><div class="api-arg-desc">This callback accepts two arguments: <code>function(roomName, fromRoomName)</code>. It can be used to calculate the cost of entering that room. You can use this to do things like prioritize your own rooms, or avoid some rooms. You can return a floating point cost or <code>Infinity</code> to block the room.</div></li></ul><p></p></td></tr></tbody></table>
---@field findRoute fun(fromRoom:any,toRoom:any,opts:any?):({exit:string,room:string}[])
--- <p>Get the linear distance (in rooms) between two rooms. You can use this function to estimate the energy cost of sending resources through terminals, or using observers and nukes.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>roomName1</code></td><td>string</td><td><p>The name of the first room.</p></td></tr><tr><td><code>roomName2</code></td><td>string</td><td><p>The name of the second room.</p></td></tr><tr><td><code>continuous</code><br/><em>optional</em></td><td>boolean</td><td><p>Whether to treat the world map continuous on borders. Set to true if you want to calculate the trade or terminal send cost. Default is false.</p></td></tr></tbody></table>
---@field getRoomLinearDistance fun(roomName1:any,roomName2:any,continuous:any?)
--- <p>Get a <a href="https://docs.screeps.com/api/#Room-Terrain"><code>Room.Terrain</code></a> object which provides fast access to static terrain data. This method works for any room in the world even if you have no access to it.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>roomName</code></td><td>string</td><td><p>The room name.</p></td></tr></tbody></table>
---@field getRoomTerrain fun(roomName:any)
--- <div class="api-deprecated"><p>This method is deprecated and will be removed soon. Please use a faster method <a href="https://docs.screeps.com/api/#Game.map.getRoomTerrain"><code>Game.map.getRoomTerrain</code></a> instead.</p></div> <p>Get terrain type at the specified room position. This method works for any room in the world even if you have no access to it.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>x</code></td><td>number</td><td><p>X position in the room.</p></td></tr><tr><td><code>y</code></td><td>number</td><td><p>Y position in the room.</p></td></tr><tr><td><code>roomName</code></td><td>string</td><td><p>The room name.</p></td></tr><tr><td><code>pos</code></td><td><a href="https://docs.screeps.com/api/#RoomPosition">RoomPosition</a></td><td><p>The position object.</p></td></tr></tbody></table>
---@field getTerrainAt fun(x:any,y:any,roomName:any)|fun(pos:any)
--- <p>Returns the world size as a number of rooms between world corners. For example, for a world with rooms from W50N50 to E50S50 this method will return 102.</p>
---@field getWorldSize fun()
--- <div class="api-deprecated"><p>This method is deprecated and will be removed soon. Please use <a href="https://docs.screeps.com/api/#Game.map.getRoomStatus"><code>Game.map.getRoomStatus</code></a> instead.</p></div> <p>Check if the room is available to move into.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>roomName</code></td><td>string</td><td><p>The room name.</p></td></tr></tbody></table>
---@field isRoomAvailable fun(roomName:any)
--- <p>Gets availablity status of the room with the specified name. Learn more about starting areas from <a href="https://docs.screeps.com/start-areas.html">this article</a>.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>roomName</code></td><td>string</td><td><p>The room name.</p></td></tr></tbody></table>
---@field getRoomStatus fun(roomName:any)
---@field visual Game.map.visual
local map = {}

--- <p>Map visuals provide a way to show various visual debug info on the game map. You can use the <code>Game.map.visual</code> object to draw simple shapes that are visible only to you. </p> <p>Map visuals are not stored in the database, their only purpose is to display something in your browser. All drawings will persist for one tick and will disappear if not updated. All <code>Game.map.visual</code> calls have no added CPU cost (their cost is natural and mostly related to simple <code>JSON.serialize</code> calls). However, there is a usage limit: you cannot post more than 1000 KB of serialized data. </p> <p>All draw coordinates are measured in global game coordinates (<a href="https://docs.screeps.com/api/#RoomPosition"><code>RoomPosition</code></a>).</p>
---@class Game.map.visual
--- <p>Draw a line.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>pos1</code></td><td><a href="https://docs.screeps.com/api/#RoomPosition">RoomPosition</a></td><td><p>The start position object.</p></td></tr><tr><td><code>pos2</code></td><td><a href="https://docs.screeps.com/api/#RoomPosition">RoomPosition</a></td><td><p>The finish position object.</p></td></tr><tr><td><code>style</code><br/><em>optional</em></td><td>object</td><td><p>An object with the following properties:</p><ul><li><div class="api-arg-title">width</div><div class="api-arg-type">number</div><div class="api-arg-desc">Line width, default is 0.1.</div></li><li><div class="api-arg-title">color</div><div class="api-arg-type">string</div><div class="api-arg-desc">Line color in the following format: <code>#ffffff</code> (hex triplet). Default is #ffffff.</div></li><li><div class="api-arg-title">opacity</div><div class="api-arg-type">number</div><div class="api-arg-desc">Opacity value, default is 0.5.</div></li><li><div class="api-arg-title">lineStyle</div><div class="api-arg-type">string</div><div class="api-arg-desc">Either <code>undefined</code> (solid line), <code>dashed</code>, or <code>dotted</code>. Default is undefined.</div></li></ul></td></tr></tbody></table>
---@field line fun(pos1:any,pos2:any,style:any?)
--- <p>Draw a circle.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>pos</code></td><td><a href="https://docs.screeps.com/api/#RoomPosition">RoomPosition</a></td><td><p>The position object of the center.</p></td></tr><tr><td><code>style</code><br/><em>optional</em></td><td>object</td><td><p>An object with the following properties:</p><ul><li><div class="api-arg-title">radius</div><div class="api-arg-type">number</div><div class="api-arg-desc">Circle radius, default is 10.</div></li><li><div class="api-arg-title">fill</div><div class="api-arg-type">string</div><div class="api-arg-desc">Fill color in the following format: <code>#ffffff</code> (hex triplet). Default is #ffffff.</div></li><li><div class="api-arg-title">opacity</div><div class="api-arg-type">number</div><div class="api-arg-desc">Opacity value, default is 0.5.</div></li><li><div class="api-arg-title">stroke</div><div class="api-arg-type">string</div><div class="api-arg-desc">Stroke color in the following format: <code>#ffffff</code> (hex triplet). Default is undefined (no stroke).</div></li><li><div class="api-arg-title">strokeWidth</div><div class="api-arg-type">number</div><div class="api-arg-desc">Stroke line width, default is 0.5.</div></li><li><div class="api-arg-title">lineStyle</div><div class="api-arg-type">string</div><div class="api-arg-desc">Either <code>undefined</code> (solid line), <code>dashed</code>, or <code>dotted</code>. Default is undefined.</div></li></ul></td></tr></tbody></table>
---@field circle fun(pos:any,style:any?)
--- <p>Draw a rectangle.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>topLeftPos</code></td><td><a href="https://docs.screeps.com/api/#RoomPosition">RoomPosition</a></td><td><p>The position object of the top-left corner.</p></td></tr><tr><td><code>width</code></td><td>number</td><td><p>The width of the rectangle.</p></td></tr><tr><td><code>height</code></td><td>number</td><td><p>The height of the rectangle.</p></td></tr><tr><td><code>style</code><br/><em>optional</em></td><td>object</td><td><p>An object with the following properties:</p><ul><li><div class="api-arg-title">fill</div><div class="api-arg-type">string</div><div class="api-arg-desc">Fill color in the following format: <code>#ffffff</code> (hex triplet). Default is #ffffff.</div></li><li><div class="api-arg-title">opacity</div><div class="api-arg-type">number</div><div class="api-arg-desc">Opacity value, default is 0.5.</div></li><li><div class="api-arg-title">stroke</div><div class="api-arg-type">string</div><div class="api-arg-desc">Stroke color in the following format: <code>#ffffff</code> (hex triplet). Default is undefined (no stroke).</div></li><li><div class="api-arg-title">strokeWidth</div><div class="api-arg-type">number</div><div class="api-arg-desc">Stroke line width, default is 0.5.</div></li><li><div class="api-arg-title">lineStyle</div><div class="api-arg-type">string</div><div class="api-arg-desc">Either <code>undefined</code> (solid line), <code>dashed</code>, or <code>dotted</code>. Default is undefined.</div></li></ul></td></tr></tbody></table>
---@field rect fun(topLeftPos:any,width:any,height:any,style:any?)
--- <p>Draw a polyline.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>points</code></td><td>array</td><td><p>An array of points. Every item should be a <a href="https://docs.screeps.com/api/#RoomPosition"><code>RoomPosition</code></a> object.</p></td></tr><tr><td><code>style</code><br/><em>optional</em></td><td>object</td><td><p>An object with the following properties:                    </p><ul><li><div class="api-arg-title">fill</div><div class="api-arg-type">string</div><div class="api-arg-desc">Fill color in the following format: <code>#ffffff</code> (hex triplet). Default is <code>undefined</code> (no fill).</div></li><li><div class="api-arg-title">opacity</div><div class="api-arg-type">number</div><div class="api-arg-desc">Opacity value, default is 0.5.</div></li><li><div class="api-arg-title">stroke</div><div class="api-arg-type">string</div><div class="api-arg-desc">Stroke color in the following format: <code>#ffffff</code> (hex triplet). Default is #ffffff.</div></li><li><div class="api-arg-title">strokeWidth</div><div class="api-arg-type">number</div><div class="api-arg-desc">Stroke line width, default is 0.5.</div></li><li><div class="api-arg-title">lineStyle</div><div class="api-arg-type">string</div><div class="api-arg-desc">Either <code>undefined</code> (solid line), <code>dashed</code>, or <code>dotted</code>. Default is undefined.</div></li></ul><p></p></td></tr></tbody></table>
---@field poly fun(points:any,style:any?)
--- <p>Draw a text label. You can use any valid Unicode characters, including <a href="http://unicode.org/emoji/charts/emoji-style.txt" target="_blank">emoji</a>.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>text</code></td><td>string</td><td><p>The text message.</p></td></tr><tr><td><code>pos</code></td><td><a href="https://docs.screeps.com/api/#RoomPosition">RoomPosition</a></td><td><p>The position object of the label baseline.</p></td></tr><tr><td><code>style</code><br/><em>optional</em></td><td>object</td><td><p>An object with the following properties:                    </p><ul><li><div class="api-arg-title">color</div><div class="api-arg-type">string</div><div class="api-arg-desc">Font color in the following format: <code>#ffffff</code> (hex triplet). Default is #ffffff.</div></li><li><div class="api-arg-title">fontFamily</div><div class="api-arg-type">string</div><div class="api-arg-desc">The font family, default is <code>sans-serif</code></div></li><li><div class="api-arg-title">fontSize</div><div class="api-arg-type">number</div><div class="api-arg-desc">The font size in game coordinates, default is 10</div></li><li><div class="api-arg-title">fontStyle</div><div class="api-arg-type">string</div><div class="api-arg-desc">The font style ('normal', 'italic' or 'oblique')</div></li><li><div class="api-arg-title">fontVariant</div><div class="api-arg-type">string</div><div class="api-arg-desc">The font variant ('normal' or 'small-caps')</div></li><li><div class="api-arg-title">stroke</div><div class="api-arg-type">string</div><div class="api-arg-desc">Stroke color in the following format: <code>#ffffff</code> (hex triplet). Default is undefined (no stroke).</div></li><li><div class="api-arg-title">strokeWidth</div><div class="api-arg-type">number</div><div class="api-arg-desc">Stroke width, default is 0.15.</div></li><li><div class="api-arg-title">backgroundColor</div><div class="api-arg-type">string</div><div class="api-arg-desc">Background color in the following format: <code>#ffffff</code> (hex triplet). Default is undefined (no background). When background is enabled, text vertical align is set to middle (default is baseline).</div></li><li><div class="api-arg-title">backgroundPadding</div><div class="api-arg-type">number</div><div class="api-arg-desc">Background rectangle padding, default is 2.</div></li><li><div class="api-arg-title">align</div><div class="api-arg-type">string</div><div class="api-arg-desc">Text align, either <code>center</code>, <code>left</code>, or <code>right</code>. Default is <code>center</code>.</div></li><li><div class="api-arg-title">opacity</div><div class="api-arg-type">number</div><div class="api-arg-desc">Opacity value, default is 0.5.</div></li></ul><p></p></td></tr></tbody></table>
---@field text fun(text:any,pos:any,style:any?)
--- <p>Remove all visuals from the map.</p>
---@field clear fun()
--- <p>Get the stored size of all visuals added on the map in the current tick. It must not exceed 1024,000 (1000 KB).</p>
---@field getSize fun()
--- <p>Returns a compact representation of all visuals added on the map in the current tick.</p>
---@field export fun()
--- <p>Add previously exported (with <a href="https://docs.screeps.com/api/#Game.map-visual.export">Game.map.visual.export</a>) map visuals to the map visual data of the current tick. </p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>val</code></td><td>string</td><td><p>The string returned from Game.map.visual.export.</p></td></tr></tbody></table>
---@field import fun(val:any)
local visual = {}

--- <p>A global object representing the in-game market. You can use this object to track resource transactions to/from your terminals, and your buy/sell orders.</p> <p>Learn more about the market system from <a href="https://docs.screeps.com/market.html">this article</a>.</p>
---@class Game.market
--- <p>Your current credits balance.</p>
---@field credits number
--- <p>An array of the last 100 incoming transactions to your terminals with the following format:</p>
---@field incomingTransactions any[]
--- <p>An array of the last 100 outgoing transactions from your terminals with the following format:</p>
---@field outgoingTransactions any[]
--- <p>Estimate the energy transaction cost of <a href="https://docs.screeps.com/api/#StructureTerminal.send"><code>StructureTerminal.send</code></a> and <a href="https://docs.screeps.com/api/#Game.market.deal"><code>Game.market.deal</code></a> methods. The formula:</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>amount</code></td><td>number</td><td><p>Amount of resources to be sent.</p></td></tr><tr><td><code>roomName1</code></td><td>string</td><td><p>The name of the first room.</p></td></tr><tr><td><code>roomName2</code></td><td>string</td><td><p>The name of the second room.</p></td></tr></tbody></table>
---@field calcTransactionCost fun(amount:any,roomName1:any,roomName2:any)
--- <p>Cancel a previously created order. The 5% fee is not returned.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>orderId</code></td><td>string</td><td><p>The order ID as provided in <code>Game.market.orders</code>.</p></td></tr></tbody></table>
---@field cancelOrder fun(orderId:any)
--- <p>Change the price of an existing order. If <code>newPrice</code> is greater than old price, you will be charged <code>(newPrice-oldPrice)*remainingAmount*0.05</code> credits.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>orderId</code></td><td>string</td><td><p>The order ID as provided in <code>Game.market.orders</code>.</p></td></tr><tr><td><code>newPrice</code></td><td>number</td><td><p>The new order price.</p></td></tr></tbody></table>
---@field changeOrderPrice fun(orderId:any,newPrice:any)
--- <p>Create a market order in your terminal. You will be charged <code>price*amount*0.05</code> credits when the order is placed. The maximum orders count is 300 per player. You can create an order at any time with any amount, it will be automatically activated and deactivated depending on the resource/credits availability.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>params</code></td><td>object</td><td><p>An object with the following params:</p><ul><li><div class="api-arg-title">type</div><div class="api-arg-type">string</div><div class="api-arg-desc">The order type, either <code>ORDER_SELL</code> or <code>ORDER_BUY</code>.</div></li><li><div class="api-arg-title">resourceType</div><div class="api-arg-type">string</div><div class="api-arg-desc">Either one of the <code>RESOURCE_*</code> constants or one of account-bound resources (See <code>INTERSHARD_RESOURCES</code> constant). If your Terminal doesn't have the specified resource, the order will be temporary inactive.</div></li><li><div class="api-arg-title">price</div><div class="api-arg-type">number</div><div class="api-arg-desc">The price for one resource unit in credits. Can be a decimal number.</div></li><li><div class="api-arg-title">totalAmount</div><div class="api-arg-type">number</div><div class="api-arg-desc">The amount of resources to be traded in total.</div></li><li><div class="api-arg-title">roomName (optional)</div><div class="api-arg-type">string</div><div class="api-arg-desc">The room where your order will be created. You must have your own Terminal structure in this room, otherwise the created order will be temporary inactive. This argument is not used when <code>resourceType</code> is one of account-bound resources (See <code>INTERSHARD_RESOURCES</code> constant).</div></li><br/></ul></td></tr></tbody></table>
---@field createOrder fun(params:any)
--- <p>Execute a trade deal from your Terminal in <code>yourRoomName</code> to another player's Terminal using the specified buy/sell order. Your Terminal will be charged energy units of transfer cost regardless of the order resource type. You can use <a href="https://docs.screeps.com/api/#calcTransactionCost"><code>Game.market.calcTransactionCost</code></a> method to estimate it. When multiple players try to execute the same deal, the one with the shortest distance takes precedence. You cannot execute more than 10 deals during one tick.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>orderId</code></td><td>string</td><td><p>The order ID as provided in <code>Game.market.getAllOrders</code>.</p></td></tr><tr><td><code>amount</code></td><td>number</td><td><p>The amount of resources to transfer.</p></td></tr><tr><td><code>yourRoomName</code><br/><em>optional</em></td><td>string</td><td><p>The name of your room which has to contain an active Terminal with enough amount of energy. This argument is not used when the order resource type is one of account-bound resources (See <code>INTERSHARD_RESOURCES</code> constant).</p></td></tr></tbody></table>
---@field deal fun(orderId:any,amount:any,yourRoomName:any?)
--- <p>Add more capacity to an existing order. It will affect <code>remainingAmount</code> and <code>totalAmount</code> properties. You will be charged <code>price*addAmount*0.05</code> credits.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>orderId</code></td><td>string</td><td><p>The order ID as provided in <code>Game.market.orders</code>.</p></td></tr><tr><td><code>addAmount</code></td><td>number</td><td><p>How much capacity to add. Cannot be a negative value.</p></td></tr></tbody></table>
---@field extendOrder fun(orderId:any,addAmount:any)
--- <p>Get other players' orders currently active on the market. This method supports internal indexing by <code>resourceType</code>.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>filter</code><br/><em>optional</em></td><td>object, function</td><td><p>An object or function that will filter the resulting list using the <a href="https://lodash.com/docs#filter" rel="noopener" target="_blank"><code>lodash.filter</code></a> method.</p></td></tr></tbody></table>
---@field getAllOrders fun(filter:any?)
--- <p>Get daily price history of the specified resource on the market for the last 14 days. </p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>resourceType</code><br/><em>optional</em></td><td>string</td><td><p>One of the <code>RESOURCE_*</code> constants. If undefined, returns history data for all resources.</p></td></tr></tbody></table>
---@field getHistory fun(resourceType:any?):({resourceType:string,date:string,transactions:integer,volume:integer,avgPrice:number,stddevPrice:number}[])
--- <p>Retrieve info for specific market order.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>id</code></td><td>string</td><td><p>The order ID.</p></td></tr></tbody></table>
---@field getOrderById fun(id:any)
---@field orders Game.market.orders
local market = {}

--- <p>An object with your active and inactive buy/sell orders on the market.See<a href="https://docs.screeps.com/api/#getAllOrders"><code>getAllOrders</code></a>for properties explanation.</p>
---@class Game.market.orders
local orders = {}

--- <p>An object with your global resources that are bound to the account, like pixels or cpu unlocks. Each object key is a resource constant, values are resources amounts.</p>
---@class Game.resources
local resources = {}

--- <p>An object describing the world shard where your script is currently being executed in.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>name</code></td><td>string</td><td><p>The name of the shard.</p></td></tr><tr><td><code>type</code></td><td>string</td><td><p>Currently always equals to <code>normal</code>.</p></td></tr><tr><td><code>ptr</code></td><td>boolean</td><td><p>Whether this shard belongs to the <a href="https://docs.screeps.com/ptr.html">PTR</a>.</p></td></tr></tbody></table>
---@class Game.shard
local shard = {}
