-- WARNING: THIS FILE IS GENERATED, DO NOT MODIFY.


--- <p><img align="right" src="./Screeps Documentation_files/visual.png"/></p> <p>Room visuals provide a way to show various visual debug info in game rooms. You can use the <code>RoomVisual</code> object to draw simple shapes that are visible only to you. Every existing <code>Room</code> object already contains the <a href="https://docs.screeps.com/api/#Room.visual"><code>visual</code></a> property, but you also can create new <code>RoomVisual</code> objects for any room (even without visibility) using the <a href="https://docs.screeps.com/api/#RoomVisual.constructor">constructor</a>.</p> <p>Room visuals are not stored in the database, their only purpose is to display something in your browser. All drawings will persist for one tick and will disappear if not updated. All <code>RoomVisual</code> API calls have no added CPU cost (their cost is natural and mostly related to simple <code>JSON.serialize</code> calls). However, there is a usage limit: you cannot post more than 500 KB  of serialized data per one room (see <a href="https://docs.screeps.com/api/#RoomVisual.getSize"><code>getSize</code></a> method).</p> <p>All draw coordinates are measured in game coordinates and centered to tile centers, i.e. (10,10) will point to the center of the creep at <code>x:10; y:10</code> position. Fractional coordinates are allowed.</p>
---@class RoomVisual
--- <p>The name of the room.</p>
---@field roomName string
--- <p>Draw a line.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>x1</code></td><td>number</td><td><p>The start X coordinate.</p></td></tr><tr><td><code>y1</code></td><td>number</td><td><p>The start Y coordinate.</p></td></tr><tr><td><code>x2</code></td><td>number</td><td><p>The finish X coordinate.</p></td></tr><tr><td><code>y2</code></td><td>number</td><td><p>The finish Y coordinate.</p></td></tr><tr><td><code>pos1</code></td><td><a href="https://docs.screeps.com/api/#RoomPosition">RoomPosition</a></td><td><p>The start position object.</p></td></tr><tr><td><code>pos2</code></td><td><a href="https://docs.screeps.com/api/#RoomPosition">RoomPosition</a></td><td><p>The finish position object.</p></td></tr><tr><td><code>style</code><br/><em>optional</em></td><td>object</td><td><p>An object with the following properties:</p><ul><li><div class="api-arg-title">width</div><div class="api-arg-type">number</div><div class="api-arg-desc">Line width, default is 0.1.</div></li><li><div class="api-arg-title">color</div><div class="api-arg-type">string</div><div class="api-arg-desc">Line color in any web format, default is <code>#ffffff</code> (white).</div></li><li><div class="api-arg-title">opacity</div><div class="api-arg-type">number</div><div class="api-arg-desc">Opacity value, default is 0.5.</div></li><li><div class="api-arg-title">lineStyle</div><div class="api-arg-type">string</div><div class="api-arg-desc">Either <code>undefined</code> (solid line), <code>dashed</code>, or <code>dotted</code>. Default is undefined.</div></li></ul></td></tr></tbody></table>
---@field line fun(x1:any,y1:any,x2:any,y2:any,style:any?)|fun(pos1:any,pos2:any,style:any?)
--- <p>Draw a circle.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>x</code></td><td>number</td><td><p>The X coordinate of the center.</p></td></tr><tr><td><code>y</code></td><td>number</td><td><p>The Y coordinate of the center.</p></td></tr><tr><td><code>pos</code></td><td><a href="https://docs.screeps.com/api/#RoomPosition">RoomPosition</a></td><td><p>The position object of the center.</p></td></tr><tr><td><code>style</code><br/><em>optional</em></td><td>object</td><td><p>An object with the following properties:</p><ul><li><div class="api-arg-title">radius</div><div class="api-arg-type">number</div><div class="api-arg-desc">Circle radius, default is 0.15.</div></li><li><div class="api-arg-title">fill</div><div class="api-arg-type">string</div><div class="api-arg-desc">Fill color in any web format, default is <code>#ffffff</code> (white).</div></li><li><div class="api-arg-title">opacity</div><div class="api-arg-type">number</div><div class="api-arg-desc">Opacity value, default is 0.5.</div></li><li><div class="api-arg-title">stroke</div><div class="api-arg-type">string</div><div class="api-arg-desc">Stroke color in any web format, default is undefined (no stroke).</div></li><li><div class="api-arg-title">strokeWidth</div><div class="api-arg-type">number</div><div class="api-arg-desc">Stroke line width, default is 0.1.</div></li><li><div class="api-arg-title">lineStyle</div><div class="api-arg-type">string</div><div class="api-arg-desc">Either <code>undefined</code> (solid line), <code>dashed</code>, or <code>dotted</code>. Default is undefined.</div></li></ul></td></tr></tbody></table>
---@field circle fun(x:any,y:any,style:any?)|fun(pos:any,style:any?)
--- <p>Draw a rectangle.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>x</code></td><td>number</td><td><p>The X coordinate of the top-left corner.</p></td></tr><tr><td><code>y</code></td><td>number</td><td><p>The Y coordinate of the top-left corner.</p></td></tr><tr><td><code>topLeftPos</code></td><td><a href="https://docs.screeps.com/api/#RoomPosition">RoomPosition</a></td><td><p>The position object of the top-left corner.</p></td></tr><tr><td><code>width</code></td><td>number</td><td><p>The width of the rectangle.</p></td></tr><tr><td><code>height</code></td><td>number</td><td><p>The height of the rectangle.</p></td></tr><tr><td><code>style</code><br/><em>optional</em></td><td>object</td><td><p>An object with the following properties:</p><ul><li><div class="api-arg-title">fill</div><div class="api-arg-type">string</div><div class="api-arg-desc">Fill color in any web format, default is <code>#ffffff</code> (white).</div></li><li><div class="api-arg-title">opacity</div><div class="api-arg-type">number</div><div class="api-arg-desc">Opacity value, default is 0.5.</div></li><li><div class="api-arg-title">stroke</div><div class="api-arg-type">string</div><div class="api-arg-desc">Stroke color in any web format, default is undefined (no stroke).</div></li><li><div class="api-arg-title">strokeWidth</div><div class="api-arg-type">number</div><div class="api-arg-desc">Stroke line width, default is 0.1.</div></li><li><div class="api-arg-title">lineStyle</div><div class="api-arg-type">string</div><div class="api-arg-desc">Either <code>undefined</code> (solid line), <code>dashed</code>, or <code>dotted</code>. Default is undefined.</div></li></ul></td></tr></tbody></table>
---@field rect fun(x:any,y:any,width:any,height:any,style:any?)|fun(topLeftPos:any,width:any,height:any,style:any?)
--- <p>Draw a polyline.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>points</code></td><td>array</td><td><p>An array of points. Every item should be either an array with 2 numbers (i.e. <code>[10,15]</code>), or a <a href="https://docs.screeps.com/api/#RoomPosition"><code>RoomPosition</code></a> object.</p></td></tr><tr><td><code>style</code><br/><em>optional</em></td><td>object</td><td><p>An object with the following properties:                    </p><ul><li><div class="api-arg-title">fill</div><div class="api-arg-type">string</div><div class="api-arg-desc">Fill color in any web format, default is <code>undefined</code> (no fill).</div></li><li><div class="api-arg-title">opacity</div><div class="api-arg-type">number</div><div class="api-arg-desc">Opacity value, default is 0.5.</div></li><li><div class="api-arg-title">stroke</div><div class="api-arg-type">string</div><div class="api-arg-desc">Stroke color in any web format, default is <code>#ffffff</code> (white).</div></li><li><div class="api-arg-title">strokeWidth</div><div class="api-arg-type">number</div><div class="api-arg-desc">Stroke line width, default is 0.1.</div></li><li><div class="api-arg-title">lineStyle</div><div class="api-arg-type">string</div><div class="api-arg-desc">Either <code>undefined</code> (solid line), <code>dashed</code>, or <code>dotted</code>. Default is undefined.</div></li></ul><p></p></td></tr></tbody></table>
---@field poly fun(points:any,style:any?)
--- <p>Draw a text label. You can use any valid Unicode characters, including <a href="http://unicode.org/emoji/charts/emoji-style.txt" target="_blank">emoji</a>.</p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>text</code></td><td>string</td><td><p>The text message.</p></td></tr><tr><td><code>x</code></td><td>number</td><td><p>The X coordinate of the label baseline point.</p></td></tr><tr><td><code>y</code></td><td>number</td><td><p>The Y coordinate of the label baseline point.</p></td></tr><tr><td><code>pos</code></td><td><a href="https://docs.screeps.com/api/#RoomPosition">RoomPosition</a></td><td><p>The position object of the label baseline.</p></td></tr><tr><td><code>style</code><br/><em>optional</em></td><td>object</td><td><p>An object with the following properties:                    </p><ul><li><div class="api-arg-title">color</div><div class="api-arg-type">string</div><div class="api-arg-desc">Font color in any web format, default is <code>#ffffff</code> (white).</div></li><li><div class="api-arg-title">font</div><div class="api-arg-type">number, string</div><div class="api-arg-desc">Either a number or a string in one of the following forms:                                <ul><li><code>0.7</code> - relative size in game coordinates</li><li><code>20px</code> - absolute size in pixels</li><li><code>0.7 serif</code></li><li><code>bold italic 1.5 Times New Roman</code></li></ul></div></li><li><div class="api-arg-title">stroke</div><div class="api-arg-type">string</div><div class="api-arg-desc">Stroke color in any web format, default is undefined (no stroke).</div></li><li><div class="api-arg-title">strokeWidth</div><div class="api-arg-type">number</div><div class="api-arg-desc">Stroke width, default is 0.15.</div></li><li><div class="api-arg-title">backgroundColor</div><div class="api-arg-type">string</div><div class="api-arg-desc">Background color in any web format, default is undefined (no background). When background is enabled, text vertical align is set to middle (default is baseline).</div></li><li><div class="api-arg-title">backgroundPadding</div><div class="api-arg-type">number</div><div class="api-arg-desc">Background rectangle padding, default is 0.3.</div></li><li><div class="api-arg-title">align</div><div class="api-arg-type">string</div><div class="api-arg-desc">Text align, either <code>center</code>, <code>left</code>, or <code>right</code>. Default is <code>center</code>.</div></li><li><div class="api-arg-title">opacity</div><div class="api-arg-type">number</div><div class="api-arg-desc">Opacity value, default is 1.0.</div></li></ul><p></p></td></tr></tbody></table>
---@field text fun(text:any,x:any,y:any,style:any?)|fun(text:any,pos:any,style:any?)
--- <p>Remove all visuals from the room.</p>
---@field clear fun()
--- <p>Get the stored size of all visuals added in the room in the current tick. It must not exceed 512,000 (500 KB).</p>
---@field getSize fun()
--- <p>Returns a compact representation of all visuals added in the room in the current tick.</p>
---@field export fun()
--- <p>Add previously exported (with <a href="https://docs.screeps.com/api/#RoomVisual.export">RoomVisual.export</a>) room visuals to the room visual data of the current tick. </p> <table><thead><tr><th>parameter</th><th>type</th><th>description</th></tr></thead><tbody><tr><td><code>val</code></td><td>string</td><td><p>The string returned from RoomVisual.export.</p></td></tr></tbody></table>
---@field import fun(val:any)
local RoomVisual = {}
